### ISSUE TITLE
The app gets completely borked if using this keymap configuration instead of the default (System: OLD 2DS)

### ISSUE THREAD

**Issue by TheSandBoxMKG** [badda71/TinyVNC#1]
### The Problem
If using this keymap configuration, TinyVNC reads it but ignores it and uses the default one. But also when exiting the session, if retry button is pressed, it goes into the server selection menu but no buttons other than the D-Pad and C-Pad work and it gets stuck there. If instead quit button is pressed, the program freezes and doesn't take any more input. Also, as a result of this, when pressing the power button, the console's home menu says that it has "closed the program" but if the HOME button is pressed instead of powering it off, it goes back to the HOME menu, **but it plays the animation of the app going in background to show the HOME menu**, and as I can check, the program continues to be in background despite going through the power-off screen. Trying to close the program results in a "closing program…" dialog that lasts forever (So I had to use the Rosalina menu to power off the console).
### The Configuration
```
# mappings as per https://libvnc.github.io/doc/html/keysym_8h_source.html
# 1 = toggle keyboard
# 2 = disconnect
# 3-7 = mouse button 1-5 (1=left, 2=middle, 3=right, 4=wheelup, 5=wheeldown
# 8 = toggle scaling
# 9 = toggle bottom screen backlight
A	0xFF0D
B	0xFF1B
X	0x002F
Y	0x0066
L	0x0003
R	0x0003
ZL	0x0000
ZR	0x0000
START	0x003A
SELECT	0x0002
CPAD_UP	0x006B
CPAD_DOWN	0x006A
CPAD_LEFT	0x0068
CPAD_RIGHT	0x006C
DPAD_UP	0x004B
DPAD_DOWN	0x004A
DPAD_LEFT	0x0048
DPAD_RIGHT	0x004C
CSTCK_UP	0x0000
CSTCK_DOWN	0x0000
CSTCK_LEFT	0x0000
CSTCK_RIGHT	0x0000
```
### How to reproduce the problem
1. Use said keymap configuration
2. Connect to VNC Server
3. Disconnect by any means

**Retry**
4. Press the Ⓐ button to retry
5. Try to do anything in the menu
6. Nothing happens

**Quit**
4. Press the Ⓑ button to quit
5. Press any button
6. Nothing happens
7. Press POWER button
8. Press HOME button when the screen before fully powering off appears
9. Program going into background animation plays out
10. Close program
11. Console gets stuck in closing program dialog
### System
- Old 2DS
No other systems have been tried.

**Comment by TheSandBoxMKG** [comment]
**UPDATE:** Either mapping the non-relevant keys to other than `0x0000` or simply removing them altogether from the configuration file seems to fix the problem with the program ignoring the keymap configuration. The problem of the program not being able to shut down correctly still remains.

**Comment by badda71** [comment]
fixed with https://github.com/badda71/TinyVNC/commit/284073472ccd4bc220a5ce7faa12d0044bec2d48
