### ISSUE TITLE
Screen does not refresh

### ISSUE THREAD

**Issue by Mitchell128134** [badda71/TinyVNC#2]
Connecting to VMWare built in VNC client, and I can confirm everything is working, but it does not refresh on the 3ds client.

**Comment by badda71** [comment]
I cannot really reproduce the issue. Could you provide more details?

**Comment by Mitchell128134** [comment]
Not really because it kinda went away in most circumstances? I have no idea
what causes it. The screen will just randomly decide to freeze frame, and
then I can usually fix it by reconnected.

**Comment by badda71** [comment]
Cannot reproduce
