### ISSUE TITLE
App refuses to connect despite the password being correct

### ISSUE THREAD

**Issue by SKCro** [badda71/TinyVNC#3]
TinyVNC refuses to connect to my PC despite the input password being correct. Oddly, changing the screen resolution to an unsupported resolution gets rid of the "failed to verify password" issue, but obviously, it still won't connect. I find it weird that it at least attempts to connect when the resolution is high, but doesn't even try when I lower the resolution. I'm using a New 3DS if that helps. The resolution that I'm trying to use is 1024x768 (which shouldn't be an issue)

**Comment by badda71** [comment]
Can you give some details about your server? Which software, what are you settings, etc.?

**Comment by SKCro** [comment]
Sorry, didn't notice your reply until just now :sweat_smile: 
I managed to solve the issue by disabling encryption and some other stuff. Thanks anyway!
