### ISSUE TITLE
TinyVNC crashes when there is a “:”

### ISSUE THREAD

**Issue by TheGhostboi64** [badda71/TinyVNC#5]
So I was about to use my VNC server right? and somehow it crashes whenever you put an “:” in username. this might be a bug.

**Comment by badda71** [comment]
Which VNC server are you using?

**Comment by TheGhostboi64** [comment]
> Which VNC server are you using?

I think I’m using a alpine Linux server, it was when I didn’t know what the :0 meant before my name, but I solved it, thanks to some dude on discord, I Had to use my ip to connect to it besides. I’m just saying when you edit anything in tinyvnc, it’ll crash if you put a : symbol.

**Comment by TheGhostboi64** [comment]
And the VNC server was preconfigured as well

**Comment by badda71** [comment]
Hm, I cannot really reproduce the issue. What exactly are you typing in which field and when does TinyVNC crash?

**Comment by TheGhostboi64** [comment]
> 

I typed in “NintendoZone:0” on where it asks for the vnc  IP address when that happened

**Comment by badda71** [comment]
fixed by https://github.com/badda71/TinyVNC/commit/845498e7bc9e26043049aced68b4dc1956a9eadf
